---
title: "Proposal"
author: "Tiffany Xi"
date: "11/4/2018"
output: github_document
---

### The group members (names and UNIs)

Tian Li (tl2882)
Huaqing Xi(hx2263)
Shuwei Liu (sl4471)
Yueming Kou (yk2826)
Yizhi Ma (ym2715)

### The tentative project title

The distribution of characteristics of HIV/AIDS Diagnoses in New York City from 2010 to 2013

### The motivation for this project

We try to explore the potential relationship between different characteristics of patients and diagnoses, in order to get more information about  HIV/AIDS.

### The intended final products

an elaborate final report, website and short video

### The anticipated data sources

HIV/AIDS Diagnoses by Neighborhood, Age Group, and Race/Ethnicity
from NYC open data
https://data.cityofnewyork.us/Health/HIV-AIDS-Diagnoses-by-Neighborhood-Age-Group-and-R/dxnu-p2qd

### The planned analyses / visualizations / coding challenges

how to organize the original big data 
how to convert neighbourhood variable into location coordinate and visualize it
maybe some relationships are not obvious or just caused by randomization

### The planned timeline

Nov.12 Finish in-person meeting
Nov.13 Find some related works and learn
Nov.14 Set the plans
Nov.17 Data cleaning and wrangling
Nov.18 Initial visualization and research relevent supplement data
Nov.23 Shiny？
Nov.30 Finish written report with detailed project description
Dec.02 Write webpage 
Dec.04 Finish speech draft and record screencast
Dec.06 DDL!

### Data discription:

This dataset includes data on new diagnoses of HIV and AIDS in NYC for the calendar years 2010 through 2013. Reported cases and case rates (per 100,000 population) are stratified by age group, race/ethnicity, and United Hospital Fund (UHF) neighborhood. For more information, please visit the HIV/AIDS Surveillance Data module on EpiQuery: nyc.gov/health/epiquery

